version: 2
updates:
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: aws/aws-sdk-php
    versions:
    - 3.171.20
    - 3.173.0
    - 3.173.1
    - 3.173.11
    - 3.173.2
    - 3.173.20
    - 3.173.26
    - 3.173.27
    - 3.173.5
    - 3.175.1
    - 3.176.3
    - 3.176.6
    - 3.176.8
    - 3.178.4
  - dependency-name: symfony/var-dumper
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
    - 5.2.5
  - dependency-name: symfony/http-kernel
    versions:
    - 5.2.2
    - 5.2.3
    - 5.2.4
    - 5.2.5
  - dependency-name: symfony/process
    versions:
    - 5.2.2
    - 5.2.3
  - dependency-name: symfony/stopwatch
    versions:
    - 5.2.1
    - 5.2.2
    - 5.2.3
  - dependency-name: laravel/framework
    versions:
    - 7.30.3
  - dependency-name: ramsey/collection
    versions:
    - 1.1.1
  - dependency-name: symfony/deprecation-contracts
    versions:
    - 2.2.0
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "06:00"
    timezone: Asia/Tokyo
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: uikit
    versions:
    - 3.6.14
    - 3.6.15
    - 3.6.16
    - 3.6.17
    - 3.6.18
    - 3.6.19
  - dependency-name: sass
    versions:
    - 1.32.5
    - 1.32.6
    - 1.32.7
    - 1.32.8
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.0
  - dependency-name: lodash
    versions:
    - 4.17.20
