@startuml Create New Entity Sequence
UI_View -> UI_Action: Send Parameters From View
activate UI_Action

UI_Action -> ApplicationService_Usecase: Request Usecase Execution

activate ApplicationService_Usecase
ApplicationService_Usecase -> ApplicationService_Repository: Execute Usecase With Domain knowledge

activate ApplicationService_Repository
ApplicationService_Repository -> DomainModel_Entity: Create Entity
DomainModel_Entity -> ApplicationService_Repository: Return Entity
 ApplicationService_Repository -> Infrastructure_RDBMS: Persist Entity

activate Infrastructure_RDBMS
ApplicationService_Repository <- Infrastructure_RDBMS: Return Persistance Response
deactivate Infrastructure_RDBMS

ApplicationService_Usecase <-- ApplicationService_Repository: Return Usecase Execution Response
deactivate ApplicationService_Repository

ApplicationService_Usecase -> DomainEvent: Fire Async DomainEvent if neccessary(ex: send mail)

UI_Action <-- ApplicationService_Usecase: Return Usecase Execution Response
deactivate ApplicationService_Usecase

UI_View <-- UI_Action: Return Presenter like Responder
deactivate UI_Action

@enduml
