name: laravel-tweet-ddd
on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: 708u/laravel-alpine:7.4.3-node-browser
      env:
        APP_ENV: testing
        APP_URL: http://localhost
        DB_CONNECTION: mysql
        DB_HOST: mysql
        DB_DATABASE: laravel_tweet_ddd_testing
        CACHE_DRIVER: redis
        QUEUE_CONNECTION: redis
        SESSION_DRIVER: redis
        MAIL_DRIVER: log
        MAIL_HOST: smtp.mailtrap.io
        MAIL_PORT: 2525
        MAIL_FROM_ADDRESS: from@example.com
        MAIL_FROM_NAME: Laravel-tweet
        REDIS_HOST: redis
        DUSK_BASE_URL: http://localhost:8000
        CHROME_DRIVER_HOST: http://localhost:9515
        TELESCOPE_ENABLED: false
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: laravel_tweet_ddd_testing
          MYSQL_ROOT_PASSWORD: root
          MYSQL_ROOT_HOST: "%"
      redis:
        image: redis:5.0.7-alpine
    steps:
      - uses: actions/checkout@v2
      - run: cp .env.example .env

      # Install dependencies
      - name: Cache composer vendor
        uses: actions/cache@v1
        env:
          cache-name: cache-composer-vendor
        with:
          path: vendor
          key: ${{ runner.os }}-${{ env.cache-name }}-v1-${{ hashFiles('**/composer.lock') }}
      - run: composer install
      - name: Cache node_modules
        uses: actions/cache@v1
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-v1-${{ hashFiles('**/yarn.lock') }}

      # Format Check
      - run: ./vendor/bin/php-cs-fixer fix --config=./.php_cs.dist --dry-run -v

      - run: yarn
      - run: yarn prod
      - run: php artisan key:generate

      # cache config
      - run: php artisan config:cache

      # Determine if laravel application successfully loaded
      - run: php artisan
      - run: php artisan route:list

      # Unit test
      - run: php artisan migrate
      - run: vendor/bin/phpunit

      # E2E test with dusk. Comment in these run if you use it.
      - run: chromedriver --whitelisted-ips > /dev/null 2>&1 &
      - run: php artisan serve > /dev/null 2>&1 &
      - run: php artisan dusk

      # Archive Artifacts
      - name: Archive screenshots
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: e2e-screenshots
          path: tests/Browser/screenshots
      - name: Archive laravel log
        uses: actions/upload-artifact@v1
        if: always()
        with:
          name: laravel-log
          path: storage/logs

      # - name: Slack Success notification
      #   uses: rtCamp/action-slack-notify@v2.0.0
      #   if: success()
      #   env:
      #     SLACK_TITLE: CI status
      #     SLACK_MESSAGE: "success :owl:"
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      # - name: Slack failed notification
      #   uses: rtCamp/action-slack-notify@v2.0.0
      #   if: failure()
      #   env:
      #     SLACK_COLOR: '#dc143c'
      #     SLACK_TITLE: CI status
      #     SLACK_MESSAGE: "Failed... :cry:"
      #     SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

      - uses: 8398a7/action-slack@v2
        with:
          text: ':owl:'
          status: ${{ job.status }}
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }} # required
        if: always() # Pick up events even if the job fails or is canceled.
